import { RouteInfo } from './sidebar.metadata';
export const ROUTES: RouteInfo[] = [
  {
    path: '',
    title: 'MENUITEMS.MAIN.TEXT',
    iconType: '',
    icon: '',
    class: '',
    groupTitle: true,
    badge: '',
    badgeClass: '',
    role: ['All'],
    submenu: [],
  },

  // Admin Modules
  {
    path: '/admin/dashboard/main',
    title: 'MENUITEMS.DASHBOARD.TEXT',
    iconType: 'material-icons-two-tone',
    icon: 'space_dashboard',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['admin'],
    submenu: [],
  },
  {
    path: '/admin/booking/offline',
    title: 'Offline Booking',
    iconType: 'material-icons-two-tone',
    icon: 'book',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['admin'],
    submenu: [],
  },

  {
    path: '/admin/booking/online',
    title: 'Online Consultation',
    iconType: 'material-icons-two-tone',
    icon: 'book',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['admin'],
    submenu: [],
  },
  {
    path: '/admin/homeVisit',
    title: 'Home Visit',
    iconType: 'material-icons-two-tone',
    icon: 'book',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['admin'],
    submenu: [],
  },
  {
    path: '/admin/specialty/all-specialty',
    title: 'Specialty',
    iconType: 'material-icons-two-tone',
    icon: 'business_center',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['admin'],
    submenu: [],
  },
  {
    path: '/admin/slides/all-slide',
    title: 'Slides',
    iconType: 'material-icons-two-tone',
    icon: 'business_center',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['admin'],
    submenu: [],
  },
  {
    path: '/admin/doctors/allDoctors',
    title: 'MENUITEMS.DOCTORS.TEXT',
    iconType: 'material-icons-two-tone',
    icon: 'supervised_user_circle',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['admin'],
    submenu: [],
  },
  {
    path: '/admin/schedule',
    title: 'Schedule',
    iconType: 'material-icons-two-tone',
    icon: 'schedule',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['admin'],
    submenu: [],
  },
  {
    path: '/admin/service',
    title: 'Service',
    iconType: 'material-icons-two-tone',
    icon: 'chrome_reader_mode',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['admin'],
    submenu: [],
  },
  {
    path: '/admin/serviceGroup',
    title: 'Sub-Service',
    iconType: 'material-icons-two-tone',
    icon: 'chrome_reader_mode',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['admin'],
    submenu: [],
  },

  {
    path: '/admin/blogs',
    title: 'Blogs',
    iconType: 'material-icons-two-tone',
    icon: 'chrome_reader_mode',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['admin'],
    submenu: [],
  },

  {
    path: '/admin/users/view-users',
    title: 'Users',
    iconType: 'material-icons-two-tone',
    icon: 'business_center',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['admin'],
    submenu: [],
  },
  {
    path: '/admin/Board',
    title: 'Board',
    iconType: 'material-icons-two-tone',
    icon: 'assignment_ind',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['admin'],
    submenu: [],
  },
  {
    path: '/admin/WebSettings/all-web-settings',
    title: 'Web Settings',
    iconType: 'material-icons-two-tone',
    icon: 'settings',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['admin'],
    submenu: [],
  },

  {
    path: '/admin/about/all-about',
    title: 'About Us',
    iconType: 'material-icons-two-tone',
    icon: 'info',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['admin'],
    submenu: [],
  },
  {
    path: '/admin/feedback',
    title: 'Feedback',
    iconType: 'material-icons-two-tone',
    icon: 'feedback',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['admin'],
    submenu: [],
  },
];
